OFFSET NPC160 ;447700
; TOAD MAN - RAIN FLUSH GENERATOR
; This NPC is generated by the Toad Man NPC during its attack state. When generated,
; it will do nothing. On frame 8, it will create a screen-spanning hurtbox for a
; single frame and generate all of the Toad Man - Rain Flush NPCs that act as the
; visual component to the attack. After that, this NPC is despawned.

#DEFINE

LEFT_DAMAGE_RANGE = 1A000
UP_DAMAGE_RANGE = 1A000
RIGHT_DAMAGE_RANGE = 1A000
DOWN_DAMAGE_RANGE = 1A000
DAMAGE_INFLICTED = 8
NPC_TO_SPAWN = A1

#ENDDEFINE

ENTER 0, 0
SETPOINTER

CMP NPC.ScriptTimer, 8
JE :SetAttack ;at 8 frames, set up the hurtbox and spawn the visual NPCs
CMP NPC.ScriptTimer, 8
JG :DestroyNPC ;after the attack and NPCs have been set up, despawn this NPC
INC NPC.ScriptTimer
JMP :EndOfCode

:DestroyNPC
MOV NPC.InUse, 0
JMP :EndOfCode

:SetAttack
MOV NPC.HitRectL, LEFT_DAMAGE_RANGE
MOV NPC.HitRectU, UP_DAMAGE_RANGE
MOV NPC.HitRectR, RIGHT_DAMAGE_RANGE
MOV NPC.HitRectD, DOWN_DAMAGE_RANGE
MOV NPC.Damage, DAMAGE_INFLICTED

;spawn the NPCs
XOR EDX, EDX
PUSH EDX ;with this entity slot... 
PUSH EDX ;with no parent or tracker... 
PUSH EDX ;with no particular direction...
PUSH EDX ;with no Y velocity... 
PUSH EDX ;with no X velocity... 
MOV EDX, 19600
PUSH EDX ;Y position
MOV EDX, 10E00
PUSH EDX ;X position
PUSH NPC_TO_SPAWN
CALL CreateNPC ;spawn the NPC 
MOV [ESP+4], 15200
CALL CreateNPC ;update Y and X, reuse previous arguments, spawn another
MOV [ESP+4], 19600
CALL CreateNPC ;spawn another
MOV [ESP+8], 1200
MOV [ESP+4], 2000
CALL CreateNPC ;spawn another
MOV [ESP+4], BA00
CALL CreateNPC ;spawn another
MOV [ESP+4], FA00
CALL CreateNPC ;spawn another
MOV [ESP+8], 1E000
MOV [ESP+4], 13E00
CALL CreateNPC ;spawn another
MOV [ESP+8], 1200
MOV [ESP+4], 18200
CALL CreateNPC ;spawn another
MOV [ESP+8], 1E000
MOV [ESP+4], 1C600
CALL CreateNPC ;spawn another
MOV [ESP+8], 1200
MOV [ESP+4], 20800
CALL CreateNPC ;spawn another
MOV [ESP+8], 8600
MOV [ESP+4], 25A00
CALL CreateNPC ;spawn another
MOV [ESP+8], 19400
CALL CreateNPC ;spawn another
MOV [ESP+8], 10E00
CALL CreateNPC ;spawn another
MOV [ESP+8], 4200
MOV [ESP+4], 21A00
CALL CreateNPC ;spawn another
MOV [ESP+8], CA00
CALL CreateNPC ;spawn another
MOV [ESP+8], 15000
CALL CreateNPC ;spawn another
MOV [ESP+8], 8800
MOV [ESP+4], 8400
CALL CreateNPC ;spawn another
MOV [ESP+8], 7600
MOV [ESP+4], DA00
CALL CreateNPC ;spawn another
MOV [ESP+8], 9800
MOV [ESP+4], FA00
CALL CreateNPC ;spawn another
MOV [ESP+8], AA00
CALL CreateNPC ;spawn another
MOV [ESP+8], 8600
MOV [ESP+4], 19400
CALL CreateNPC ;spawn another
MOV [ESP+8], DA00
MOV [ESP+4], 7400
CALL CreateNPC ;spawn another
MOV [ESP+4], 18200
CALL CreateNPC ;spawn another
MOV [ESP+8], E800
MOV [ESP+4], 11E00
CALL CreateNPC ;spawn another
MOV [ESP+8], 11E00
MOV [ESP+4], 7400
CALL CreateNPC ;spawn another
MOV [ESP+8], 10E00
MOV [ESP+4], 19400
CALL CreateNPC ;spawn another
MOV [ESP+8], 12E00
MOV [ESP+4], 1B600
CALL CreateNPC ;spawn another
MOV [ESP+8], 14000
MOV [ESP+4], 2000
CALL CreateNPC ;spawn another
MOV [ESP+8], 17200
MOV [ESP+4], A800
CALL CreateNPC ;spawn another
MOV [ESP+4], DA00
CALL CreateNPC ;spawn another
ADD ESP, 20 ;fix the stack
SETPOINTER

INC NPC.ScriptTimer

:EndOfCode
LEAVE
RETN